---
# necessary steps to configure the role

- name: install base condarc
  sudo: no
  copy: src={{ item }} dest="~/.{{ item }}"
  with_items:
    - condarc
  when: miniconda_add_condarc

- name: add miniconda to the PATH
  sudo: no
  shell: "echo '{{ item }}' >> {{ miniconda_rcfile }} executable=/bin/bash"
  with_items:
    - "export PATH={{ miniconda_home }}/bin:$PATH"
  when: miniconda_modify_path

- name: update conda to latest version
  sudo: no
  shell: "{{ miniconda_home }}/bin/conda update conda --yes -q executable=/bin/bash"

- name: create environments
  sudo: no
  shell: "{{ miniconda_home }}/bin/conda create --yes -q -n {{ item.name }} python={{ item.python_version }} {{ item.pkgs }} creates={{ miniconda_home }}/envs/{{ item.name }}"
  when: miniconda_installed | success
  with_items: miniconda_environments
